# Netlify config

# Security + sensible defaults for all files
[[headers]]
  for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Correct MIME for the web manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
  Content-Type = "application/manifest+json"
  Cache-Control = "public, max-age=3600"

# Don’t aggressively cache the service worker itself
[[headers]]
  for = "/service-worker.js"
  [headers.values]
  Cache-Control = "no-cache"

# Help crawlers: cache but not too long
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
  Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
  Cache-Control = "public, max-age=3600"
